language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
solution: "./TextualRealityExperienceEngine/TextualRealityExperienceEngine.sln"
script:
  - dotnet restore
  - dotnet build
  - dotnet test